SELECT * FROM  sapiens_db1.aluno;
SELECT * FROM sapiens_db1.aluno WHERE CURSO="ENGENHARIA DA COMPUTAÇÃO";
SELECT * FROM sapiens_db1.aluno WHERE CURSO="SISTEMAS DE INFORMAÇÃO";
SELECT * FROM sapiens_db1.aluno WHERE CURSO="JOGOS DIGITAIS"; 
SELECT * FROM sapiens_db1.aluno WHERE CURSO="ANALISE E DESENVOLVIMENTO DE SISTEMAS"; 